branches:
  only:
    - master
    - dev

language: python

services:
  - docker

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install '.[test,dev]' .

before_install:
  - docker-compose up -d
  - docker ps -a

script:
  - pytest
